name: Test module
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
        with:
          version: v1.9.0
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_PASSWORD }}
          ftpUrl: ${{ secrets.GH_FTP_URL }}
